#!/usr/bin/env bash
# Configures an Ubuntu server so that localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

if grep -q "facebook.com" /etc/hosts; then
    sed -i 's/.*facebook\.com.*/8.8.8.8 facebook.com/' /etc/hosts
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
