#!/usr/bin/env bash
# Configures local hostname resolution for localhost and facebook.com

sed -i 's/127\.0\.0\.1\([[:space:]]\+localhost\)/127.0.0.2\1/g' /etc/hosts

if grep -q "facebook.com" /etc/hosts; then
    sed -i 's/.*facebook\.com.*/8.8.8.8 facebook.com/g' /etc/hosts
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
